<script lang="ts">
  /**
   * Print barcode labels for a set of units (CLAUDE.md §13, Phase B).
   *
   * The PDF is generated by the server at exact physical dimensions, because a
   * browser's print scaling drifts a few millimetres and a sheet of adhesive
   * labels is ruined by that (internal/stockroom/barcode.go). This dialog only
   * picks what to print, on which sheet, and where to start on it.
   *
   * Every unit starts ticked. An empty selection is refused by the server
   * rather than read as "everything", and the button is disabled for it here.
   */
  import { Button } from "@stockroom/ui/components/ui/button"
  import { Checkbox } from "@stockroom/ui/components/ui/checkbox"
  import * as Dialog from "@stockroom/ui/components/ui/dialog"
  import { Input } from "@stockroom/ui/components/ui/input"
  import { Label } from "@stockroom/ui/components/ui/label"
  import * as api from "../../api/index"
  import type { LabelLayout } from "../../api/types"
  import { saveBlob } from "../../download"

  export interface LabelItem {
    id: string
    name: string
    serial: string
  }

  let { open = $bindable(false), items }: { open?: boolean; items: LabelItem[] } = $props()

  let layouts = $state<LabelLayout[]>([])
  let layoutKey = $state("")
  /**
   * The sheets come in both paper sizes, and a school only ever buys one, so the
   * list shows that one's three or four rather than all eight. The first guess
   * follows the browser's locale: US Letter in the US and Canada, A4 elsewhere.
   */
  let paper = $state(
    typeof navigator !== "undefined" && /-(US|CA)$/i.test(navigator.language) ? "US Letter" : "A4",
  )
  let startAt = $state("0")
  let chosen = $state<Record<string, boolean>>({})
  let busy = $state(false)
  let error = $state<string | null>(null)

  // Re-tick everything each time the dialog opens on a new set.
  $effect(() => {
    if (!open) return
    chosen = Object.fromEntries(items.map((i) => [i.id, true]))
    error = null
    if (layouts.length === 0) {
      api.labelLayouts().then(
        (list) => {
          layouts = list
          // The one whose hint says "start here", else the first.
          if (!list.some((l) => l.paper === paper)) paper = list[0]?.paper ?? paper
          const onPaper = list.filter((l) => l.paper === paper)
          layoutKey ||= (onPaper.find((l) => /start here/i.test(l.hint)) ?? onPaper[0])?.key ?? ""
        },
        (err) => (error = err instanceof Error ? err.message : String(err)),
      )
    }
  })

  const layout = $derived(layouts.find((l) => l.key === layoutKey))
  const papers = $derived([...new Set(layouts.map((l) => l.paper))])
  const shownLayouts = $derived(layouts.filter((l) => l.paper === paper))

  /** Switching paper keeps the size: medium on Letter becomes medium on A4. */
  function choosePaper(next: string) {
    paper = next
    const size = layout?.key.split("-")[0]
    const same = shownLayouts.find((l) => l.key.split("-")[0] === size)
    layoutKey = (same ?? shownLayouts[0])?.key ?? ""
  }
  const selected = $derived(items.filter((i) => chosen[i.id]))
  /** Serials the chosen size cannot fit; the server refuses them, so say so first. */
  const tooLong = $derived(
    layout ? selected.filter((i) => i.serial.length > layout.max_serial_chars) : [],
  )

  async function print() {
    busy = true
    error = null
    try {
      const skip = Number(startAt.trim() || "0")
      if (!Number.isInteger(skip) || skip < 0) throw new Error("Skip must be a whole number, 0 or more.")
      const pdf = await api.assetLabels({
        asset_ids: selected.map((i) => i.id),
        layout: layoutKey,
        start_at: skip,
      })
      saveBlob(pdf, `stockroom-labels-${selected.length}.pdf`)
      open = false
    } catch (err) {
      error = err instanceof Error ? err.message : String(err)
    } finally {
      busy = false
    }
  }
</script>

<Dialog.Root bind:open>
  <Dialog.Content class="max-w-lg">
    <Dialog.Header>
      <Dialog.Title>Print labels</Dialog.Title>
      <Dialog.Description>
        A PDF at the exact size of the sheet. Print it at <strong>100% / actual size</strong> —
        “fit to page” shrinks it and every label misses its square.
      </Dialog.Description>
    </Dialog.Header>

    <div class="flex flex-col gap-1.5">
      <div class="flex items-center justify-between gap-2">
        <Label>Label sheet</Label>
        {#if papers.length > 1}
          <div class="flex gap-1" role="radiogroup" aria-label="Paper size">
            {#each papers as p (p)}
              <Button
                size="sm"
                variant={p === paper ? "secondary" : "ghost"}
                role="radio"
                aria-checked={p === paper}
                onclick={() => choosePaper(p)}>{p}</Button
              >
            {/each}
          </div>
        {/if}
      </div>
      <div class="flex flex-col gap-1">
        {#each shownLayouts as l (l.key)}
          <label class="flex cursor-pointer items-start gap-2 rounded-(--radius) p-1 hover:bg-raised">
            <input type="radio" name="label-layout" value={l.key} bind:group={layoutKey} class="mt-1 accent-(--primary)" />
            <span class="flex flex-col">
              <span class="text-sm text-fg">{l.label}</span>
              <span class="text-xs text-fg-faint">{l.hint} Serials up to about {l.max_serial_chars} characters.</span>
            </span>
          </label>
        {/each}
      </div>
    </div>

    <div class="flex flex-col gap-1.5">
      <Label for="label-skip">Skip labels already used on the first sheet</Label>
      <Input id="label-skip" bind:value={startAt} inputmode="numeric" class="w-24" />
    </div>

    <div class="flex flex-col gap-1.5">
      <Label>Units ({selected.length} of {items.length})</Label>
      <div class="flex max-h-40 flex-col gap-1 overflow-y-auto">
        {#each items as item (item.id)}
          <label class="flex items-center gap-2 text-sm">
            <Checkbox
              checked={chosen[item.id] ?? false}
              onCheckedChange={(v) => (chosen = { ...chosen, [item.id]: v === true })}
            />
            <span class="font-mono text-xs">{item.serial}</span>
            <span class="truncate text-fg-muted">{item.name}</span>
          </label>
        {/each}
      </div>
    </div>

    {#if tooLong.length}
      <p class="text-sm text-status-overdue" role="alert">
        {tooLong.length} serial{tooLong.length === 1 ? " is" : "s are"} probably too long for this size
        ({tooLong.slice(0, 3).map((i) => i.serial).join(", ")}{tooLong.length > 3 ? ", …" : ""}).
        The limit is approximate and the server has the final say; a bigger label is the safe
        choice.
      </p>
    {/if}
    {#if error}
      <p class="text-sm text-status-overdue" role="alert">{error}</p>
    {/if}

    <Dialog.Footer>
      <Button variant="ghost" onclick={() => (open = false)}>Cancel</Button>
      <Button disabled={busy || selected.length === 0 || !layoutKey } onclick={print}>
        {busy ? "Making the PDF…" : `Download ${selected.length} label${selected.length === 1 ? "" : "s"}`}
      </Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>
